_app.i18n.en.main = 
  about: 'About'
  add: 'add'
  addNew: 'add new'
  address: 'address'
  agreement: 'User Agreement'
  amount: 'amount'
  confirm: 'confirm'
  contact: 'contact'
  contacts: 'contacts'
  contactUs: 'Contact us'
  content: 'content'
  copyRight: -> "© #{new Date().getFullYear()} <a target='_blank' href='https://veliovgroup.com' itemprop='url'><span itemprop='name'>Veliov Group LLC.</span></a> All rights reserved."
  date: 'date'
  docs: 'Documentation'
  email: 'email'
  emails: 'emails'
  features: 'Features'
  free: 'Free'
  goToServer: 'Open Server'
  impl10n: 'Add or improve translation'
  isActive: 'active'
  item: 'record'
  length: 'length'
  loading: 'loading...'
  loadMore: 'load more'
  message: 'message'
  phone: 'phone'
  phoneNumber: 'phone number'
  phones: 'phones'
  plan: 'Plan'
  pp: 'Privacy policy'
  price: 'price'
  pricing: 'Pricing'
  remove: 'remove'
  save: 'Save'
  saved: 'Saved'
  send: 'Send'
  sending: 'sending...'
  server: 'server'
  showContent: 'Show Content'
  showMessages: 'Show Messages'
  showMore: 'Show More'
  signIn: 'Sign In'
  signUp: 'Sign Up'
  subject: 'subject'
  submit: 'submit'
  submitIssue: 'Submit an issue'
  tnc: 'Terms and Conditions'
  type: 'type'
  unseen: 'unseen'
  value: 'value'
  verify: 'verify'

