_app.i18n.en.sidebar = 
  home: 'Home'
  websites: 'Servers'
  notifications: 'Notifications'
  billing: 'Billing'
  settings: 'Settings'
  contacts: 'Contacts'
  referral: 'Referral program'
  passwd: 'Change password'
  logout: 'Log Out'