_app.i18n.ru.main = 
  about: 'О сервисе'
  add: 'добавить'
  addNew: 'добавить новый'
  address: 'адрес'
  agreement: 'Пользовательское соглашение'
  amount: 'сумма'
  confirm: 'подтвердить'
  contact: 'контакт'
  contacts: 'контакты'
  contactUs: 'Обратная связь'
  content: 'контент'
  copyRight: -> "© #{new Date().getFullYear()} <a target='_blank' href='https://veliovgroup.com' itemprop='url'><span itemprop='name'>Veliov Group LLC.</span></a> Все права защищены."
  date: 'дата'
  docs: 'Документация'
  email: 'email'
  emails: 'emails'
  features: 'Функционал'
  free: 'бесплатно'
  goToServer: 'Открыть Сервер'
  impl10n: 'Добавить или улучшить перевод'
  isActive: 'вкл.'
  item: 'запись'
  length: 'длина'
  loading: 'загружаю...'
  loadMore: 'показать еще'
  message: 'сообщение'
  phone: 'телефон'
  phoneNumber: 'телефонный номер'
  phones: 'телефоны'
  plan: 'План'
  pp: 'Политика конфиденциальности'
  price: 'цена'
  pricing: 'Тарифы'
  remove: 'удалить'
  save: 'Сохранить'
  saved: 'Сохранено'
  send: 'Отправить'
  sending: 'отправляю...'
  set: 'Установить'
  server: 'сервер'
  showContent: 'Показать контент'
  showMessages: 'Показать сообщения'
  showMore: 'Показать еще'
  signIn: 'Войти'
  signUp: 'Регистрация'
  subject: 'тема'
  submit: 'отправить'
  submitIssue: 'Сообщить об ошибке'
  tnc: 'Условия и положения'
  type: 'тип'
  unseen: 'не прочитано'
  value: 'значение'
  verify: 'подтвердить'
