_app.i18n.ru.sidebar = 
  home: 'Главная'
  websites: 'Сервера'
  notifications: 'Уведомления'
  billing: 'Баланс'
  settings: 'Настройки'
  contacts: 'Контакты'
  referral: 'Пригласи друга'
  passwd: 'Сменить пароль'
  logout: 'Выход'